# KITTI Training Configuration

# Overall
mode: train
model_name: kitti_train
pretrain: ./swin_large_patch4_window12_384_22k.pth

# Dataset
dataset: kitti
data_path: /media/staging1/zyzeng/kitti_raw_data/
gt_path: /media/staging1/zyzeng/ground_truth/
filenames_file: data_splits/eigen_train_files_with_gt.txt
input_height: 352
input_width: 1216
max_depth: 80
prior_mean: 2.54

# Training
batch_size: 3
num_epochs: 50
learning_rate: 3.0e-5
end_learning_rate: 1.0e-5
weight_decay: 0.0
adam_eps: 1.0e-3
num_threads: 1

# Preprocessing
do_kb_crop: true

# Log and save
log_directory: ./models/
log_freq: 200

# Online evaluation
do_online_eval: true
eval_freq: 2500
data_path_eval: /media/staging1/zyzeng/kitti_raw_data/
gt_path_eval: /media/staging1/zyzeng/ground_truth/
filenames_file_eval: data_splits/eigen_test_files_with_gt.txt
min_depth_eval: 1.0e-3
max_depth_eval: 80
garg_crop: true

# WorDepth
weight_kld: 1.0e-3
alter_prob: 0.5
