# NYU Depth V2 Training Configuration

# Overall
mode: train
model_name: nyu_train
pretrain: ./swin_large_patch4_window12_384_22k.pth

# Dataset
dataset: nyu
data_path: /media/staging1/zyzeng/nyu_depth_v2/sync/
gt_path: /media/staging1/zyzeng/nyu_depth_v2/sync/
filenames_file: ./data_splits/nyudepthv2_train_files_with_gt.txt
input_height: 480
input_width: 640
max_depth: 10

# Training
batch_size: 4
num_epochs: 50
learning_rate: 3.0e-5
end_learning_rate: 1.0e-5
weight_decay: 0.0
adam_eps: 1.0e-3
num_threads: 1

# Preprocessing
do_random_rotate: true
degree: 2.5

# Log and save
log_directory: ./models/
log_freq: 100

# Online evaluation
do_online_eval: true
eval_freq: 2500
data_path_eval: /media/staging1/zyzeng/nyu_depth_v2/official_splits/test/
gt_path_eval: /media/staging1/zyzeng/nyu_depth_v2/official_splits/test/
filenames_file_eval: ./data_splits/nyudepthv2_test_files_with_gt.txt
min_depth_eval: 1.0e-3
max_depth_eval: 10
eigen_crop: true

# WorDepth
weight_kld: 1.0e-3
alter_prob: 0.5
